SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;



CREATE TABLE IF NOT EXISTS public."Competidores"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Nome" text COLLATE pg_catalog."default",
    "Sexo" text COLLATE pg_catalog."default",
    "TemperaturaMediaCorpo" numeric NOT NULL,
    "Peso" numeric NOT NULL,
    "Altura" numeric NOT NULL,
    CONSTRAINT "PK_Competidores" PRIMARY KEY ("Id")
);
	
	
-- Table: public.PistasCorrida

CREATE TABLE IF NOT EXISTS public."PistasCorrida"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Descricao" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_PistasCorrida" PRIMARY KEY ("Id")
);
	
-- Table: public.HistoricosCorrida

CREATE TABLE IF NOT EXISTS public."HistoricosCorrida"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "DataCorrida" timestamp without time zone NOT NULL,
    "TempoGasto" numeric NOT NULL,
    "CompetidorId" integer,
    "PistaCorridaId" integer,
    CONSTRAINT "PK_HistoricosCorrida" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_HistoricosCorrida_Competidores_CompetidorId" FOREIGN KEY ("CompetidorId")
        REFERENCES public."Competidores" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT,
    CONSTRAINT "FK_HistoricosCorrida_PistasCorrida_PistaCorridaId" FOREIGN KEY ("PistaCorridaId")
        REFERENCES public."PistasCorrida" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT
);



CREATE INDEX IF NOT EXISTS "IX_HistoricosCorrida_CompetidorId"
    ON public."HistoricosCorrida" USING btree
    ("CompetidorId" ASC NULLS LAST);    
-- Index: IX_HistoricosCorrida_PistaCorridaId

-- DROP INDEX IF EXISTS public."IX_HistoricosCorrida_PistaCorridaId";

CREATE INDEX IF NOT EXISTS "IX_HistoricosCorrida_PistaCorridaId"
    ON public."HistoricosCorrida" USING btree
    ("PistaCorridaId" ASC NULLS LAST)
    TABLESPACE pg_default;	
	
	
	
--INSERT INTO public."Competidores"("Id", "Nome", "Sexo", "TemperaturaMediaCorpo", "Peso", "Altura")
--VALUES
--(1,'Richard','M',36,79.0,1.75),
--(2,'Richard2','M',36,79.0,1.75);



--INSERT INTO public."PistasCorrida"("Id","Descricao")
--(1,'PistaUm'),
--(2,'PistaDois'),
--(3,'PistaTres');



--INSERT INTO public."HistoricosCorrida"("Id","DataCorrida", "TempoGasto", "CompetidorId", "PistaCorridaId")
--(1,'2023-03-02 00:00:00',10,1,1),
--(2,'2023-03-01 18:25:43.511',92,1,1),
--(3,'2023-03-01 18:25:43.511',88,1,1);
	
	