// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using System;

namespace Data.Migrations
{
    [DbContext(typeof(AdventureDBContext))]
    partial class AdventureDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Domain.Competidores.Entities.Competidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("Altura")
                        .HasColumnType("numeric");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<decimal>("Peso")
                        .HasColumnType("numeric");

                    b.Property<string>("Sexo")
                        .HasColumnType("text");

                    b.Property<decimal>("TemperaturaMediaCorpo")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Competidores");
                });

            modelBuilder.Entity("Domain.HistoricosCorrida.Entities.HistoricoCorrida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("CompetidorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCorrida")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("PistaCorridaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TempoGasto")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CompetidorId");

                    b.HasIndex("PistaCorridaId");

                    b.ToTable("HistoricosCorrida");
                });

            modelBuilder.Entity("Domain.PistasCorrida.Entities.PistaCorrida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PistasCorrida");
                });

            modelBuilder.Entity("Domain.HistoricosCorrida.Entities.HistoricoCorrida", b =>
                {
                    b.HasOne("Domain.Competidores.Entities.Competidor", "Competidor")
                        .WithMany()
                        .HasForeignKey("CompetidorId");

                    b.HasOne("Domain.PistasCorrida.Entities.PistaCorrida", "PistaCorrida")
                        .WithMany()
                        .HasForeignKey("PistaCorridaId");

                    b.Navigation("Competidor");

                    b.Navigation("PistaCorrida");
                });
#pragma warning restore 612, 618
        }
    }
}
